### ISSUE TITLE
Decoding error when deleting a service

### ISSUE THREAD

**Issue by t089** [swiftkube/client#27]
```swift
do {
  try await self.client.services.delete(in: namespace, name: serviceName, options: nil)
  logger.info("Deleted service: \(serviceName)")
} catch {
  logger.error("Failed to delete service \(serviceName): \(error)")
}
```

Output: 

```
Failed to delete service test: decodingError("Couldn\'t decode response")
```

```
    {
      "identity": "client",
      "kind": "remoteSourceControl",
      "location": "https://github.com/swiftkube/client.git",
      "state": {
        "revision": "9b842812c63c9b3ebbb9142b717727f0d0ae2bb9",
        "version": "0.13.0"
      }
    },
    {
      "identity": "model",
      "kind": "remoteSourceControl",
      "location": "https://github.com/swiftkube/model.git",
      "state": {
        "revision": "f3096f4628f2b068d8f936653ebb3cc1004b095d",
        "version": "0.7.2"
      }
    }
```

```yaml
clientVersion:
  buildDate: "2022-06-15T14:22:29Z"
  compiler: gc
  gitCommit: f66044f4361b9f1f96f0053dd46cb7dce5e990a8
  gitTreeState: clean
  gitVersion: v1.24.2
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: darwin/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-11-29T18:43:31Z"
  compiler: gc
  gitCommit: 96e7d52c98a32f2b296ca7f19dc9346cf79915ba
  gitTreeState: clean
  gitVersion: v1.23.14-eks-ffeb93d
  goVersion: go1.17.13
  major: "1"
  minor: 23+
  platform: linux/amd64
```
